-- Conteudo editavel da pagina inicial (noticias, projetos, selos, servicos, contato), antes em public/data.json.
-- Os moderadores editam pela conta; as regras de cada campo ficam em src/site.js.
CREATE TABLE IF NOT EXISTS site_conteudo (
  secao TEXT PRIMARY KEY,
  dados TEXT NOT NULL,
  atualizado_em INTEGER NOT NULL DEFAULT 0,
  atualizado_por INTEGER
);

-- o que estava no data.json no momento da migracao
INSERT OR IGNORE INTO site_conteudo (secao, dados) VALUES ('noticias', '[{"data":"01/10/2026","titulo":"O coletivo ganha um site","texto":"Começamos pela versão mais simples: vitrine de livros, projetos em andamento e notícias assinadas por quem escreve. O objetivo é levar quem chega aqui até o perfil de cada autor.","autor":"Alex Jr. Kich","autor_slug":"alex-jr-kich"},{"data":"01/10/2026","titulo":"Leitura beta abre primeiro","texto":"De todos os serviços, a leitura beta é o mais simples de organizar. Ela abre antes dos outros, e os demais entram aos poucos.","autor":"Helena Prado","autor_slug":""},{"data":"01/10/2026","titulo":"Selos, não ranking","texto":"Quem ajuda ganha um selo de participação. Nenhum selo diz que uma pessoa é melhor que outra, para que ninguém se afaste por não conseguir ser assíduo.","autor":"R. Tavares","autor_slug":""}]');
INSERT OR IGNORE INTO site_conteudo (secao, dados) VALUES ('projetos', '[{"titulo":"A Arquitetura do Silêncio","autor":"Helena Prado","autor_slug":"","genero":"Romance","etapa":"Em escrita","pct":68,"previsao":"mar/2027","sinopse":"Uma arquiteta retorna à cidade natal para demolir o prédio que projetou aos vinte anos.","trecho":"Ela desenhou aquele prédio pensando em luz. Vinte anos depois, descobriu que havia projetado sombra para todo mundo que amava.","c1":"#2b1a4a","c2":"#0e0a1a"},{"titulo":"Fio Terra","autor":"M. Sato","autor_slug":"","genero":"Antologia de contos","etapa":"Revisão","pct":92,"previsao":"dez/2026","sinopse":"Doze contos inéditos sobre pertencimento, raiz e deslocamento, a partir de uma mesma pergunta: de onde você é, de verdade?","trecho":"Não era a casa que me faltava. Era a certeza de que existia uma.","c1":"#3d2410","c2":"#150c04"},{"titulo":"Neblina","autor":"J. Ferreira","autor_slug":"","genero":"Terror","etapa":"Rascunho","pct":34,"previsao":"2027","sinopse":"Toda manhã a neblina desce sobre a vila e leva embora uma lembrança de alguém.","trecho":"","c1":"#12392e","c2":"#050f0c"}]');
INSERT OR IGNORE INTO site_conteudo (secao, dados) VALUES ('selos', '[{"nome":"Leitor beta","texto":"Leu e comentou o original de outro autor."},{"nome":"Olhar crítico","texto":"Fez leitura crítica ou revisão."},{"nome":"Divulgador","texto":"Ajudou com ideias e ações de divulgação."},{"nome":"Fundador","texto":"Esteve na construção do coletivo."}]');
INSERT OR IGNORE INTO site_conteudo (secao, dados) VALUES ('servicos', '[{"icone":"✦","titulo":"Leitura Beta","status":"Aberto","texto":"A comunidade lê o seu original antes do lançamento e devolve impressões honestas.","link":"ajuda.html","acao":"Ver pedidos"},{"icone":"✎","titulo":"Leitura crítica e revisão","status":"Em breve","texto":"Revisão ortográfica e gramatical, sugestões de estrutura e ritmo.","link":"","acao":""},{"icone":"◎","titulo":"Divulgação","status":"Em breve","texto":"Ideias de marketing, resenhas e parcerias com livrarias independentes.","link":"","acao":""},{"icone":"◈","titulo":"Capa e diagramação","status":"Em breve","texto":"Capa, miolo e versão pronta para publicação.","link":"","acao":""}]');
INSERT OR IGNORE INTO site_conteudo (secao, dados) VALUES ('contato', '{"url":""}');
